### ISSUE TITLE
A4C settings mananger cannot load certificate

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#27]
Attaching to a4c
a4c    | 2018-10-24 11:02:29 INFO  Main:53 - Creating A4C_RUNTIME_DIR dir on /mnt/a4c_runtime_data
a4c    | 2018-10-24 11:02:29 INFO  Main:66 - Write a4c conf at /opt/a4c/config/alien4cloud-config.yml
a4c    | Exception in thread "main" java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMEncryptedKeyPair
a4c    |        at es.upv.alien4cloud.settingsmanager.ConfigManager.getKey(ConfigManager.java:192)
a4c    |        at es.upv.alien4cloud.settingsmanager.ConfigManager.createJavaKeystore(ConfigManager.java:161)
a4c    |        at es.upv.alien4cloud.settingsmanager.ConfigManager.enableSsl(ConfigManager.java:114)
a4c    |        at es.upv.alien4cloud.settingsmanager.Main.main(Main.java:72)
a4c    | 2018-10-24 11:02:35 INFO  Main:66 - Write a4c conf at /opt/a4c/config/alien4cloud-config.yml
a4c    | Exception in thread "main" java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMEncryptedKeyPair

**Comment by asalic** [comment]
I only considered keys encrypted with passwords in the ConfigManager class. Added support for non-encrypted keys in PEM.

**Comment by asalic** [comment]
Added support for non pairs too https://github.com/indigo-dc/alien4cloud-deep/releases/tag/1.1-rc1

**Comment by asalic** [comment]
PEMEncryptedKeyPair support added in the settings manager.
